import csv, PIL, math
from PIL import Image
from pathlib import Path
import re


from math import sqrt, floor
PHI = (1 + sqrt(5))/2
def nth_color(n):
	n = n * PHI - floor(n * PHI)
	return (floor(n * 256), floor(n * 256 ** 2) % 256, floor(n * 256 ** 3) % 256)

START = 910
END = 2000

print('''GIMP Palette
Name: EMC HOI4 State colors
# Autogenerated. By FranchuFranchu
''')
im = Image.new("RGB", (END - START, 1))
for i in range(END - START):
	c = nth_color(START + i)
	im.putpixel((i, 0), c)
	r, g, b = c
	print(f"{r:3} {g:3} {b:3} State {START +i}")

im.save("palette.png")

